title: "LangVec - transforming vectors into a language-like structure"
description: "LangVec leverages the concept of percentile-based mapping to assign words from a lexicon to numerical values, facilitating intuitive and human-readable representations of numerical data."
tagline: "Language of Vectors"
url: "https://langvec.com"
theme: minima

logo: /assets/logo.png

author: "Copyright © 2024 Simeon Emanuilov. All rights reserved."

social_links:
  - { platform: github, user_url: "https://github.com/simeonemanuilov", icon: "fab fa-github" }
  - { platform: twitter, user_url: "https://twitter.com/s_emanuilov", icon: "fab fa-twitter" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/simeon-emanuilov/", icon: "fab fa-linkedin" }
  - { platform: google_scholar, user_url: "https://scholar.google.bg/citations?user=clJUDxcAAAAJ&hl=en&oi=ao", icon: "fas fa-graduation-cap" }

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/simeonemanuilov" }
    - { platform: twitter, user_url: "https://twitter.com/s_emanuilov" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/simeon-emanuilov/" }
    - { platform: google_scholar, user_url: "https://scholar.google.bg/citations?user=clJUDxcAAAAJ&hl=en&oi=ao" }